databases:
  - name: Concierge
    databaseName: Concierge
    user: Concierge

services:
  - type: web
    name: Concierge
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Concierge
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false