openapi: 3.0.1
info:
  title: "\U0001F386 Concierge API V1"
  version: v1
paths:
  "/events":
    get:
      summary: list events
      tags: 
      - events
      responses:
        '200':
          description: successful
    post:
      summary: create event
      tags: 
      - events
      responses:
        '200':
          description: successful
  "/events/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show event
      tags: 
      - events
      responses:
        '200':
          description: successful
    delete:
      summary: delete event
      tags: 
      - events
      responses:
        '200':
          description: successful
  "/users/{user_id}/reservations":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      tags: 
      - reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      tags: 
      - reservations
      responses:
        '200':
          description: successful
  "/users/{user_id}/reservations/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      tags: 
      - reservations
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      tags: 
      - reservations
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      tags: 
      - users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags: 
      - users
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: ancient-lake-57758.herokuapp.com/api/v1/
